{
 "title": "Encounters-old",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Encounters grouped by # of combatants : increase[15m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (numCombatants) (increase(encounter_duration_seconds_count[15m]))",
     "legendFormat": "{{numCombatants}}"
    }
   ]
  },
  {
   "title": "Average rounds/encounter grouped by number of combatants : increase[15m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (numCombatants) (increase(encounter_rounds_sum[15m])) / sum by (numCombatants) (increase(encounter_rounds_count[15m]))",
     "legendFormat": "{{numCombatants}}"
    }
   ]
  },
  {
   "title": "Encounters grouped by delta in combatant size : increase[15m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (sizeDelta) (increase(encounter_duration_seconds_count[15m]))",
     "legendFormat": "{{sizeDelta}}"
    }
   ]
  },
  {
   "title": "Average rounds/encounter grouped by sizeDelta : increase[15m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (sizeDelta) (increase(encounter_rounds_sum[15m])) / sum by (sizeDelta) (increase(encounter_rounds_count[15m]))",
     "legendFormat": "{{sizeDelta}}"
    }
   ]
  },
  {
   "title": "Average rounds/encounter grouped by crDelta : increase[15m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crDelta) (increase(encounter_rounds_sum[15m])) / sum by (crDelta) (increase(encounter_rounds_count[15m]))",
     "legendFormat": "{{crDelta}}"
    }
   ]
  },
  {
   "title": "Average rounds/encounter grouped by crDelta : increase[15m]",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (crDelta) (increase(encounter_rounds_sum[15m])) / sum by (crDelta) (increase(encounter_rounds_count[15m]))",
     "legendFormat": "{{crDelta}}"
    }
   ]
  }
 ]
}