{
 "title": "Attacks",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Roll the dice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Roll the dice... ",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(dice_rolls_count)", "legendFormat": "Overall" },
    {
     "expr": "sum by (die) (dice_rolls_count)",
     "legendFormat": "{{die}}"
    }
   ]
  },
  {
   "title": "Roll a d20 : rate [30m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (face) (rate(dice_rolls_count{die=\"d20\"}[30m]))",
     "legendFormat": "{{face}}"
    }
   ]
  },
  {
   "title": "Roll a d10 : rate[30m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (face) (rate(dice_rolls_count{die=\"d10\"}[30m]))",
     "legendFormat": "{{face}}"
    }
   ]
  },
  {
   "title": "Roll a d6 : rate[30m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (face) (rate(dice_rolls_count{die=\"d6\"}[30m]))",
     "legendFormat": "{{face}}"
    }
   ]
  },
  {
   "title": "Roll a d12 : rate[30m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (face) (rate(dice_rolls_count{die=\"d12\"}[30m]))",
     "legendFormat": "{{face}}"
    }
   ]
  },
  {
   "title": "Roll a d8 : rate[30m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (face) (rate(dice_rolls_count{die=\"d8\"}[30m]))",
     "legendFormat": "{{face}}"
    }
   ]
  },
  {
   "title": "Roll a d4 : rate[30m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (face) (rate(dice_rolls_count{die=\"d4\"}[30m]))",
     "legendFormat": "{{face}}"
    }
   ]
  },
  { "title": "Attacks by Hit or Miss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of attacks",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    { "expr": "sum(round_attacks_count)", "legendFormat": "Overall" },
    {
     "expr": "sum by (hitOrMiss)(round_attacks_count)",
     "legendFormat": "{{hitOrMiss}}"
    }
   ]
  },
  {
   "title": "Frequency of hit or miss : rate[20m]",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum by (hitOrMiss)(rate(round_attacks_count[20m]))",
     "legendFormat": "{{hitOrMiss}}"
    }
   ]
  },
  {
   "title": "Average damage by hit or miss : increase[20m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hitOrMiss)(increase(round_attacks_sum[20m])) / sum by (hitOrMiss)(increase(round_attacks_count[20m]))",
     "legendFormat": "{{hitOrMiss}}"
    }
   ]
  },
  {
   "title": "Mean average damage : increase[20m]",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum by (hitOrMiss)(increase(round_attacks_sum[20m])) / sum by (hitOrMiss)(increase(round_attacks_count[20m]))",
     "legendFormat": "{{hitOrMiss}}"
    }
   ]
  },
  {
   "title": "Attacks by type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of attacks",
     "type": "table",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 18 },
     "targets": [
      { "expr": "sum(round_attacks_count)", "legendFormat": "Overall" },
      {
       "expr": "sum by (attackType)(round_attacks_count)",
       "legendFormat": "{{attackType}}"
      }
     ]
    },
    {
     "title": "Frequency of attack type : increase[20m], log(base 2)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 18, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (attackType)(increase(round_attacks_count[20m]))",
       "legendFormat": "{{attackType}}"
      }
     ]
    },
    {
     "title": "Average damage per attack by type",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum by (attackType)(round_attacks_sum) / sum by (attackType)(round_attacks_count)",
       "legendFormat": "{{attackType}}"
      }
     ]
    },
    {
     "title": "Damage by attack type : increase[20m], log(base 2)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (attackType)(increase(round_attacks_sum[20m])) / sum by (attackType)(increase(round_attacks_count[20m]))",
       "legendFormat": "{{attackType}}"
      }
     ]
    }
   ]
  },
  { "title": "Attacks by monster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of attacks",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (attacker)(round_attacks_count)",
     "legendFormat": "{{attacker}}"
    }
   ]
  },
  {
   "title": "Damage per attack",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "sum by (attacker)(round_attacks_sum) / sum by (attacker)(round_attacks_count)",
     "legendFormat": "{{attacker}}"
    }
   ]
  },
  {
   "title": "Cumulative damage",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "sum by (attacker)(round_attacks_sum)",
     "legendFormat": "{{attacker}}"
    }
   ]
  },
  {
   "title": "Damage per attack",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (attacker)(increase(round_attacks_sum[15m])) / sum by (attacker)(increase(round_attacks_count[15m]))",
     "legendFormat": "{{attacker}}"
    }
   ]
  },
  {
   "title": "Damage per attack",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (attacker)(increase(round_attacks_sum[15m])) / sum by (attacker)(increase(round_attacks_count[15m]))",
     "legendFormat": "{{attacker}}"
    }
   ]
  }
 ]
}