{
 "title": "Encounters",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Encounters by target selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of encounters",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "targets": [
      { "expr": "sum(encounter_rounds_count)", "legendFormat": "Overall" },
      {
       "expr": "sum by (targetSelector) (encounter_rounds_count)",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    },
    {
     "title": "Encounters : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(encounter_rounds_count[30m]))",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (targetSelector) (increase(encounter_rounds_count[30m]))",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rounds / Encounter by target selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of rounds",
     "type": "table",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 2 },
     "targets": [
      { "expr": "sum (encounter_rounds_sum)", "legendFormat": "Overall" },
      {
       "expr": "sum by (targetSelector) (encounter_rounds_sum)",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    },
    {
     "title": "Rounds by target selector : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (targetSelector) (increase(encounter_rounds_sum[30m]))",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    },
    {
     "title": "Rounds/encounter by target selector : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (targetSelector) (increase(encounter_rounds_sum[30m])) / sum by (targetSelector) (increase(encounter_rounds_count[30m]))",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Encounters by number of combatants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of encounters",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "targets": [
      { "expr": "sum(encounter_rounds_count)", "legendFormat": "Overall" },
      {
       "expr": "sum by (numCombatants)(encounter_rounds_count)",
       "legendFormat": "{{numCombatants}} combatants"
      }
     ]
    },
    {
     "title": "Encounters by number of combatants : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (numCombatants)(increase(encounter_rounds_count[30m]))",
       "legendFormat": "{{numCombatants}} combatants"
      }
     ]
    }
   ]
  },
  {
   "title": "Rounds / Encounter by number of combatants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of rounds: random",
     "type": "table",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(encounter_rounds_sum{job=\"spring_monsters\"} or encounter_rounds_sum{job=\"quarkus_micrometer\"})",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (numCombatants)(encounter_rounds_sum{job=\"spring_monsters\"} or encounter_rounds_sum{job=\"quarkus_micrometer\"})",
       "legendFormat": "{{numCombatants}} combatants"
      }
     ]
    },
    {
     "title": "Rounds by number of combatants : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (numCombatants)(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m]))",
       "legendFormat": "{{numCombatants}} combatants"
      }
     ]
    },
    {
     "title": "Rounds / Encounter by number of combatants : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(encounter_rounds_sum[30m])) / sum(increase(encounter_rounds_count[30m]))",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (numCombatants)(increase(encounter_rounds_sum[30m])) / sum by (numCombatants)(increase(encounter_rounds_count[30m]))",
       "legendFormat": "{{numCombatants}} combatants"
      }
     ]
    }
   ]
  }
 ]
}