{
 "title": "Encounters by target selection",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Number of encounters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of encounters",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(encounter_rounds_count{job=\"quarkus_micrometer\"})",
     "legendFormat": "Relative health (Quarkus)"
    },
    {
     "expr": "sum(encounter_rounds_count{job=\"spring_monsters\"})",
     "legendFormat": "Random target (Spring)"
    }
   ]
  },
  {
   "title": "Encounters : increase[30m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "Relative health (Quarkus)"
    },
    {
     "expr": "sum(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]))",
     "legendFormat": "Random target (Spring)"
    }
   ]
  },
  {
   "title": "Encounters by number of combatants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Number of encounters",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (numCombatants)(encounter_rounds_count{job=\"spring_monsters\"} or encounter_rounds_count{job=\"quarkus_micrometer\"})",
     "legendFormat": "{{numCombatants}} combatants"
    },
    {
     "expr": "sum(encounter_rounds_count{job=\"spring_monsters\"} or encounter_rounds_count{job=\"quarkus_micrometer\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Encounters by number of combatants : increase[30m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (numCombatants)(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Rounds / Encounter by number of combatants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Number of rounds: random",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(encounter_rounds_sum{job=\"spring_monsters\"} or encounter_rounds_sum{job=\"quarkus_micrometer\"})",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (numCombatants)(encounter_rounds_sum{job=\"spring_monsters\"} or encounter_rounds_sum{job=\"quarkus_micrometer\"})",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Rounds by number of combatants : increase[30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (numCombatants)(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Rounds / Encounter by number of combatants : increase[30m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m])) / sum(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (numCombatants)(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m])) / sum by (numCombatants)(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Rounds / Encounter by target selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of rounds",
     "type": "table",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(encounter_rounds_sum{job=\"spring_monsters\"})",
       "legendFormat": "Spring 5 micrometer"
      },
      {
       "expr": "sum (encounter_rounds_sum{job=\"quarkus_micrometer\"})",
       "legendFormat": "Quarkus micrometer"
      },
      {
       "expr": "sum (encounter_rounds_sum{job=\"quarkus_micrometer\"} or encounter_rounds_sum{job=\"spring_monsters\"})",
       "legendFormat": "Overall"
      }
     ]
    },
    {
     "title": "Rounds : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 19, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m]))",
       "legendFormat": "Quarkus micrometer"
      },
      {
       "expr": "sum (increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m]))",
       "legendFormat": "Spring 5 micrometer"
      }
     ]
    },
    {
     "title": "Rounds/encounter : increase[30m]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 19, "x": 4, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m])) / sum (increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
       "legendFormat": "Quarkus micrometer"
      },
      {
       "expr": "sum(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m])) / sum(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]))",
       "legendFormat": "Spring 5 Micrometer"
      },
      {
       "expr": "sum(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m])) / sum(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]) or increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
       "legendFormat": "Overall"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of rounds: random",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(encounter_rounds_sum{job=\"spring_monsters\"})",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (numCombatants)(encounter_rounds_sum{job=\"spring_monsters\"})",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Rounds / Encounter by number of combatants selecting a random target: increase[30m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m])) / sum(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (numCombatants)(increase(encounter_rounds_sum{job=\"spring_monsters\"}[30m])) / sum by (numCombatants)(increase(encounter_rounds_count{job=\"spring_monsters\"}[30m]))",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Number of rounds: relativeHealth",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(encounter_rounds_sum{job=\"quarkus_micrometer\"})",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (numCombatants)(encounter_rounds_sum{job=\"quarkus_micrometer\"})",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  },
  {
   "title": "Rounds / Encounter selecting by relative health : increase[30m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 4, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m])) / sum(increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (numCombatants)(increase(encounter_rounds_sum{job=\"quarkus_micrometer\"}[30m])) / sum by (numCombatants)(increase(encounter_rounds_count{job=\"quarkus_micrometer\"}[30m]))",
     "legendFormat": "{{numCombatants}} combatants"
    }
   ]
  }
 ]
}