{
 "title": "4-creature Encounters",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Encounters by target selector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Encounters :  instant",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(encounter_rounds_count{numCombatants=\"04\"})",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (targetSelector)(encounter_rounds_count{numCombatants=\"04\"})",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    },
    {
     "title": "Encounters by targetSelector : increase[15m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (targetSelector)(encounters:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rounds / encounter by target selector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rounds : instant",
     "type": "table",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(encounter_rounds_sum{numCombatants=\"04\"})",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (targetSelector)(encounter_rounds_sum{numCombatants=\"04\"})",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    },
    {
     "title": "Rounds by targetSelector : increase[15m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (targetSelector)(rounds:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    },
    {
     "title": "Average rounds/encounter by targetSelector : increase[15m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rounds:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60) / sum(encounters:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (targetSelector)(rounds:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60) / sum by (targetSelector)(encounters:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "{{targetSelector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Encounters by difference in size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Encounters : instant",
     "type": "table",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (sizeDelta)(encounter_rounds_count{numCombatants=\"04\"})",
       "legendFormat": "sizeDelta {{sizeDelta}}"
      },
      {
       "expr": "sum(encounter_rounds_count{numCombatants=\"04\"})",
       "legendFormat": "Overall"
      }
     ]
    },
    {
     "title": "Encounters by sizeDelta : increase[15m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (sizeDelta)(encounters:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "sizeDelta {{sizeDelta}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rounds / Encounter by difference in size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rounds : instant",
     "type": "table",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(encounter_rounds_sum{numCombatants=\"04\"})",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (sizeDelta)(encounter_rounds_sum{numCombatants=\"04\"})",
       "legendFormat": "sizeDelta {{sizeDelta}}"
      }
     ]
    },
    {
     "title": "Rounds by sizeDelta : increase[15m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 4, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (sizeDelta)(rounds:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "sizeDelta {{sizeDelta}}"
      }
     ]
    },
    {
     "title": "Average rounds/encounter by sizeDelta : increase[15m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rounds:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60) / sum(encounters:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum by (sizeDelta)(rounds:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60) / sum by (sizeDelta)(encounters:encounter_rounds:rate15m{numCombatants=\"04\"} * 15 * 60)",
       "legendFormat": "sizeDelta {{sizeDelta}}"
      }
     ]
    }
   ]
  }
 ]
}